access/urls.py
from django.contrib import admin
from django.urls import path
from access import views
from access.views import *

app_name = "access"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('home/', views.home_view, name="home"),
    path('complete_archive_all/', views.complete_archive_all, name="complete_archive_all"),
    path('logout/', views.logout_view, name="logout"),
    path('create_team/', views.create_team, name="create_team"),
    path('team/<int:team_id>/', views.team_detail, name="team_detail"),
    path('team/add_member/', views.add_team_member, name="add_team_member"),
    path('friends/<int:friends_id>/', views.friends_detail, name="friends_detail"),
    path('friends/add_member/', views.add_friends_member, name="add_friends_member"),
]

base/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('depiction/',include('depiction.urls')),
    path('', include('navigation.urls')),
    path('access/', include('access.urls')),
    path('tasks/', include('todo.urls')),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='password-reset/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

depiction/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "depiction"

urlpatterns = [
    path('<int:pk>/edit_profile_page/',EditProfilePageView.as_view(),name='edit_profile_page'),
    path('<int:pk>/profile/',ShowProfilePageView.as_view(),name='show_profile_page'),
    path('password/',PasswordsChangeView.as_view(template_name='depiction/change-password.html'), name='password'),
    path('password_success/', views.password_success, name="password_success"),
]

depiction/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()

# Create your models here.
class Profile(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    user=models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    # user_profile_id=models.IntegerField(null=True)
    description = models.TextField(blank=True, null=True)
    first_name = models.TextField(blank=True, null=True)
    last_name = models.TextField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    phone_number = models.TextField(blank=True, null=True)
    username = models.TextField(blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    profile_image = models.ImageField(upload_to='profile_images', default='blank-profile-picture.png')

    def __str__(self):
        return(str(self.user)) 

    def get_absolute_url(self):
        return reverse('access:home')

depiction/forms.py
from .models import Profile
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User

class EditProfileNewForm(forms.ModelForm):
     class Meta:
       model=Profile
       fields = ('username','first_name','last_name','email','phone_number','description','date_of_birth','profile_image')

       widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'phone_number':forms.TextInput(attrs={'class':'form-control'}),
            'description':forms.Textarea(attrs={'class':'form-control'}),
            'date_of_birth':forms.DateInput(attrs={'class':'form-control'}),
        }

class PasswordChangingForm(PasswordChangeForm):
    old_password=forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control', 'type':'password'}))
    new_password1=forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    new_password2=forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))

    class Meta:
        model= User
        fields = ('old_password','new_password1','new_password2')

depiction/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import DetailView
from .models import *
from django.urls import reverse_lazy
from django.views import generic
from .forms import *

class EditProfilePageView(generic.UpdateView):
    model = Profile
    form_class=EditProfileNewForm
    template_name='depiction/edit_profile_page.html'
    def get_success_url(self):
        user_id=self.request.user.id
        user = User.objects.get(pk=user_id)
        email = self.request.POST.get('email')
        first_name = self.request.POST.get('first_name')
        last_name = self.request.POST.get('last_name')
        email = email.strip()
        if email != "":
            user.email = email
            user.save()
        user.first_name=first_name
        user.last_name=last_name
        user.save()
        return reverse_lazy('depiction:show_profile_page', args=[user_id])
    # success_url=reverse_lazy('depiction:show_profile_page', args=request.user.id)

class PasswordsChangeView(PasswordChangeView):
    form_class= PasswordChangingForm
    success_url= reverse_lazy('depiction:password_success')

def password_success(request):
    return render(request, 'depiction/password_success.html', {})

class ShowProfilePageView(DetailView):
    model = Profile
    template_name = 'depiction/my_profile.html'

    def get_context_data(self,*args,**kwargs):
        context=super(ShowProfilePageView,self).get_context_data(*args,**kwargs)
        page_user=get_object_or_404(Profile,id=self.kwargs['pk'])
        # page_user.user_profile_id=((User.objects.get(username=page_user)).id)
        # page_user.save()
        context["page_user"] = page_user
        return context

depiction/templates/depiction/change-password.html
{% extends 'depict_comp\main.html' %}
<title>Change Password</title>
{% block content %}

<div class="container" style="margin-top:20px;">
    {% include "depict_comp\navbar.html" %}
</div> 

<div class="container shadow p-3 mb-5 bg-body rounded " style="width: 50%;margin-top: 30px;">
    <h1  style="text-align:center;color:#9a35dd;margin-top: 10px;font-weight: bolder;">Change Password...</h1>
    <br/><br/>
    <div class="form-group" style="font-weight: 600;line-height: 2.5;">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p}}
            
            <button class="btn btn-primary btn-block" style="width:200px;position: relative;left:35%;
            background: linear-gradient(to right,#623dc6 ,#9a35dd );">Change Password</button>
            <br/><br/>
            <ul>
                <li class="text-muted">Your password can't be too similar to your other personal information.</li>
                <li class="text-muted">Your password must contain atleast 8 characters.</li>
                <li class="text-muted">Your password can't be a commonly used password.</li>
                <li class="text-muted">Your password can't be entirely numeric.</li>
            </ul>
        </form>
        <div class="col d-flex align-items-center justify-content-end"> 
            <input 
                class="btn btn-primary btn-block" 
                type="button" 
                value=" Back " 
                onclick="history.back()"
                style="
                    background: linear-gradient(to right,#623dc6 ,#9a35dd );
                    text-align:center;
            ">
        </div>
    </div>
</div>

{% endblock %}

depiction/templates/depiction/edit_profile_page.html
{% extends 'depict_comp\main.html' %}

<title>Edit Profile Page</title>

{% block content %}

{% if user.is_authenticated %}
<!-- {%  if user.id == profile.user.id  %} -->
    <div class="container" style="margin-top:20px;">
        {% include "depict_comp\navbar.html" %}
    </div>   
    <div class="container shadow p-3 mb-5 bg-body rounded" style="width: 50%;margin-top: 30px;">

        <h1 style="text-align:center; margin-top:10px; color:#9a35dd;font-weight: bolder;">Edit Profile Page</h1>
        <div class="form-group" style="font-weight: 600;line-height: 2.5;">
        
    
            <br/>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                {% comment %} {{ form.username }}
                {{ form.name }}
                {{ form.email }}
                {{ form.phone_number }}
                {{ form.description }}
                {{ form.profile_image }}
                <br> {% endcomment %}
                <br>
                <div class="container">
                    <div class="row align-items-start">

                    <div class="col d-flex align-items-center justify-content-center">
                        <button 
                            class="btn btn-primary btn-block" 
                            style="
                                    background: linear-gradient(to right,#623dc6 ,#9a35dd );
                                    text-align:center;
                                ">
                            Update Profile Page
                        </button>
                    </div>

                    <div class="col d-flex align-items-center justify-content-center"> 
                            <input 
                                class="btn btn-primary btn-block" 
                                type="button" 
                                value=" Back " 
                                onclick="history.back()"
                                style="
                                    background: linear-gradient(to right,#623dc6 ,#9a35dd );
                                    text-align:center;
                            ">
                    </div>
                    
                    </div>
                </div>
                {% comment %} <button class="btn btn-primary btn-block" style="width:200px;position: relative;left:35%;
                background: linear-gradient(to right,#623dc6 ,#9a35dd );">Update Profile Page</button> {% endcomment %}
            </form>
        </div>
    </div>
    <br/><br/>

    <!-- Javascript -->
    <script>
         var name="{{ user.first_name }}"
         document.getElementById("elder").placeholder=name;
    </script>

{% else %}
    Login required to view
{% endif %} 

<!-- {% else %}
You are not the correct user to edit the page
{% endif %} -->
{% endblock %}

depiction/templates/depiction/my_profile.html
{% extends 'depict_comp\main.html' %}
{% load static %} 

{% block styles %}
<link rel="stylesheet" href="{% static 'styles/otherprofile.css' %}" />
{% endblock %}

<!-- Title -->
{% block title %}
<title>Profile</title>
{% endblock %}

{% block content %}

<div class="container" style="margin-top:20px;">

    {% include "depict_comp\navbar.html" %}

    <div class="row m-b-r m-t-3"  style="margin-top:40px;">
        <div class="col-md-2 offset-md-1">
            <img src="{{ page_user.profile_image.url }}" alt="profile_image" class="img-circle rounded-circle img-fluid" style="height: 180px; width: 180px;">
        </div>
        <div class="col-md-9 p-t-2"  style="margin-top:20px;">
            <h2 class="h2-responsive">@{{page_user.username}} </h2>
            {% comment %} <form action="/follow" method="POST">
                {% csrf_token %}
            <input type="hidden" value="{{page_user.username}}" name="user" />
            <input type="hidden" value="{{request.user.username}}" name="follower" />

            {% if page_user.id != request.user.id %}
            <a data-ripple="">
            <button type="submit" class="btn btn-success follow-btn" style="position: relative;left: 300px; bottom: 40px;">{{button_text}}</button></h2>
            </a>
            {% endif %}

            <p class="profile-name">{{page_user.fname}}</p>
            <p style="position: relative;left: 20px;">{{page_user.description}}</p>
            <ul class="flex-menu">
                
                <li><strong>{{num_posts}}</strong> posts</li>
                <li><strong>{{user_followers}}</strong> followers</li>
                <li><strong>{{user_following}}</strong> following</li>
            </ul>
           </form> {% endcomment %}
        </div>
    </div>
    <hr class="border border-1 border-success">

    {% comment %} <div class="row">
        {% for post in logged_in_user_posts %}
        <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="view overlay hm-black-light m-b-2">
                <a href="{{post.image.url}}">
                <img src="{{post.image.url}}" class="img-fluid cursor-pointer" alt="" style="height: 250px;">
                </a>
            </div>
        </div>
        {% endfor %}
    </div> {% endcomment %}

        {% comment %}⬇️ Used previously ⬇️{% endcomment %}
        {% comment %} <button class="btn btn-primary btn-block" style="width:200px;position: relative;left:25%;
            background: linear-gradient(to right,#623dc6 ,#9a35dd );">
            <a href="{% url 'depiction:edit_profile_page' user.profile.id %}">Edit Profile</a>
        </button>
        <button class="btn btn-primary btn-block" style="width:200px;position: relative;left:45%;
            background: linear-gradient(to right,#623dc6 ,#9a35dd );">
            <a href="{% url 'depiction:password' %}">Change Password</a>
        </button> {% endcomment %}
        {% comment %}⬆️ Used previously ⬆️{% endcomment %}


        <div class="container">
            <div class="row align-items-start">

              <div class="col d-flex align-items-center justify-content-center">
                    <input 
                        class="btn btn-primary btn-block" 
                        type="button" 
                        value="Edit Profile" 
                        onclick="window.location.href='{% url 'depiction:edit_profile_page' user.profile.id %}'"
                        style="
                            background: linear-gradient(to right,#623dc6 ,#9a35dd );
                            text-align:center;
                    ">
              </div>

              <div class="col d-flex align-items-center justify-content-center"> 
                    <input 
                        class="btn btn-primary btn-block" 
                        type="button" 
                        value="Change Password" 
                        onclick="window.location.href='{% url 'depiction:password' %}'"
                        style="
                            background: linear-gradient(to right,#623dc6 ,#9a35dd );
                            text-align:center;
                    ">
              </div>
              
            </div>
        </div>

    <hr class="border border-1 border-success">


    

</div>

<div class="container shadow p-3 mb-5 bg-body rounded" style="width: 50%;margin-top: 30px;">

    <br>
    
    {% if page_user.first_name != null and page_user.last_name != null %}
    {% if page_user.first_name != "" and page_user.last_name != "" %}
    <h6>Full name: {{page_user.first_name}} {{page_user.last_name}}</h6><br>
    {% endif %}
    {% endif %}

    {% if page_user.email != null and page_user.email != "" %}
    <h6>Email: {{page_user.email}}</h6><br>
    {% endif %}
    <h4></h4><br>

</div>

{% endblock %}

depiction/templates/depiction/password_success.html
{% extends 'access\base_layout.html' %}
<title>Password updated</title>
{% block content %}

<div class="card container shadow p-3 mb-5 bg-body rounded" style="width: 65%;margin-top: 150px;">
    <h3 class="delete-title"  style="text-align:center;color:#9a35dd; margin-top: 10px;font-weight: bolder">Your Password Was Changed Successfully...</h3>
    <br/>
    <button style="background-color: #9a35dd;border-color: #9a35dd; width: 40%; position: relative;left: 220px;">
        <a href="{% url 'access:home' %}" style="color: #fff; text-decoration: none;">
          Go back
        </a>
    </button>
</div>

{% endblock %}