access/urls.py
from django.contrib import admin
from django.urls import path
from access import views
from access.views import *

app_name = "access"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('home/', views.home_view, name="home"),
    path('complete_archive_all/', views.complete_archive_all, name="complete_archive_all"),
    path('logout/', views.logout_view, name="logout"),
    path('create_team/', views.create_team, name="create_team"),
    path('team/<int:team_id>/', views.team_detail, name="team_detail"),
    path('team/add_member/', views.add_team_member, name="add_team_member"),
    path('friends/<int:friends_id>/', views.friends_detail, name="friends_detail"),
    path('friends/add_member/', views.add_friends_member, name="add_friends_member"),
]

base/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('depiction/',include('depiction.urls')),
    path('', include('navigation.urls')),
    path('access/', include('access.urls')),
    path('tasks/', include('todo.urls')),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='password-reset/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.contrib import admin
from django.urls import path
from todo import views


from todo.views import *

app_name = "tasks"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('create/', views.create_task, name='create'),
    path('<int:task_id>/', views.detail, name='detail'),
    path('edit/', views.edit, name='edit'),
    path('delete/<int:task_id>/', views.delete, name='delete'),
    path('complete_archive/<int:task_id>/', views.complete_archive, name='complete_archive'),
    path('not_complete_archive/<int:task_id>/', views.not_complete_archive, name='not_complete_archive'),
    path('comment/<int:task_id>', views.post_comment, name='comment'),
]

access/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Team(models.Model):
    team_name = models.CharField(max_length=50)
    members = models.ManyToManyField(User)
    created_by = models.ForeignKey(
        User, null=True, on_delete=models.CASCADE, related_name='team_created_by')

    def __str__(self):
        return self.team_name

    class Meta:
        ordering = ('team_name',)


class Friends(models.Model):
    friends_name = models.CharField(max_length=50, null=True, unique=False)
    members = models.ManyToManyField(User)
    created_by = models.ForeignKey(
        User, null=True, on_delete=models.CASCADE, related_name='friends_created_by')

    def __str__(self):
        return self.friends_name

    class Meta:
        ordering = ('friends_name',)

access/views.py
# from django.shortcuts import render

from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import redirect, render
from depiction.models import Profile

from todo.models import Task

from .models import Team, Friends


def register_view(request):
    # Check if user is authenticated, if yes then send to home
    if request.user.is_authenticated:
        return redirect('access:home')

    # Handle post request
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # After 2nd update added newly
            create_friends(request)
            profile = Profile(user=user)
            profile.save() 
            return redirect('access:home')
    else:
        # Handle login route
        form = UserCreationForm()

    return render(request, 'access/register.html', {'form': form})


def login_view(request):
    # Check if user is authenticated, if yes then send to home
    if request.user.is_authenticated:
        return redirect('access:home')

    # Handle post request
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            ''' Redirect based on next param '''
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))

            return redirect('access:home')
    else:
        form = AuthenticationForm()

    return render(request, 'access/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('access:login')


@login_required(login_url='access:login')
def home_view(request):
    # Get teams of user
    teams = request.user.team_set.all()

    # Get tasks assigned / created to user
    tasks = Task.objects.filter(
        Q(created_by=request.user) | Q(assigned_to=request.user) | Q(team__in=teams)).order_by('title').distinct()

    return render(request, 'access/home.html', {'tasks': tasks, 'teams': teams})


@login_required()
def create_team(request):
    if request.method == "POST":
        members_list = request.POST.getlist("members")
        team_name = request.POST.get("team_name")

        team = Team.objects.create(
            team_name=team_name, created_by=request.user)

        for member in members_list:
            team.members.add(User.objects.get(username=member))

        # Add creator to members
        team.members.add(request.user)

        team.save()

        # print(members)
        return redirect('access:home')

    users = User.objects.all().exclude(username=request.user.username)

    return render(request, 'access/create_team.html', {'users': users})


@login_required(login_url='access:login')
def team_detail(request, team_id):
    try:
        team = Team.objects.get(pk=team_id)
    except Team.DoesNotExist:
        messages.error(request, "Team doesn't exist")
        return redirect('access:home')

    if request.user not in team.members.all():
        messages.error(
            request, "You are not allowed to view this team's details.")
        return redirect('access:home')

    users = User.objects.all()

    tasks = Task.objects.filter(team=team)

    return render(request, 'access/team_detail.html', {'team': team, 'users': users, 'tasks': tasks})


@login_required()
def add_team_member(request):
    if request.method == 'POST':
        team_id = request.POST.get('team_id', None)

        if team_id is not None:
            try:
                team = Team.objects.get(pk=team_id)
            except Team.DoesNotExist:
                return redirect('access:home')
        else:
            return redirect('access:home')

        members = request.POST.getlist('members', None)

        if members is not None:
            for member in members:
                team.members.add(User.objects.get(username=member))

    return redirect('access:team_detail',
                    team_id=request.POST.get('team_id'))


# ----------------------------------------- After 2nd Update -------------------------------------------------------

@login_required(login_url='access:login')
def complete_archive_all(request):
    # Get teams of user
    teams = request.user.team_set.all()

    # Get tasks assigned / created to user
    tasks = Task.objects.filter(
        Q(created_by=request.user) | Q(assigned_to=request.user) | Q(team__in=teams)).order_by('title').distinct()

    return render(request, 'access/complete_archive.html', {'tasks': tasks, 'teams': teams})

@login_required()
def create_friends(request):
    if request.method == "POST":
        members_list = [] # ['Raiyan',]
        friends_name = str(request.user)+"'s Friends"

        friends = Friends.objects.create(
            friends_name=friends_name, created_by=request.user)

        for member in members_list:
            friends.members.add(User.objects.get(username=member))

        # Add creator to members
        friends.members.add(request.user)

        friends.save()

@login_required(login_url='access:login')
def friends_detail(request, friends_id):
    try:
        friends = Friends.objects.get(pk=friends_id)
    except Friends.DoesNotExist:
        messages.error(request, "Friends doesn't exist")
        return redirect('access:home')

    if request.user not in friends.members.all():
        messages.error(
            request, "You are not allowed to view this friends's details.")
        return redirect('access:home')

    users = User.objects.all()
    return render(request, 'friends/friends_detail.html', {'friends': friends, 'users': users,})

@login_required()
def add_friends_member(request):
    if request.method == 'POST':
        friends_id = request.POST.get('friends_id', None)

        if friends_id is not None:
            try:
                friends = Friends.objects.get(pk=friends_id)
            except Friends.DoesNotExist:
                return redirect('access:home')
        else:
            return redirect('access:home')

        members = request.POST.getlist('members', None)

        if members is not None:
            for member in members:
                friends.members.add(User.objects.get(username=member))

    return redirect('access:friends_detail',
                    friends_id=request.POST.get('friends_id'))

access/templates/access/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>To-Do</title>

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'logo/logo.png' %}">

    <!-- CSS Links -->
    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'access\bulma_lux.css' %}"> {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">

    <!-- JS Links -->
    <script
            defer
            src="https://use.fontawesome.com/releases/v5.0.0/js/all.js"
    ></script>
    {% block extrahead %}
    {% endblock %}
</head>
<body>


{% block content %}
{% endblock %}
</body>
</html>

access/templates/access/complete_archive.html
{% extends 'access\base_layout.html' %}

{% block content %}

    {% include "todo\navbar.html" %}

    <div class="container" style="margin-top:20px;">

        {% if messages %}
            <div class="columns" style="margin-top: 20px;">
                <div class="column"></div>
                <div class="column is-8">
                    <article class="message is-danger">
                        <div class="message-body">
                            <ul class="messages">
                                {% for message in messages %}
                                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </article>
                </div>
                <div class="column"></div>
            </div>
        {% endif %}


        <div class="columns">
            <div class="column is-7">
                <h1 class="title is-4">Tasks
                    <a href="{% url 'tasks:create' %}" style="margin-left:5px;">
                        <i class="far fa-plus-square fa-sm"></i>
                    </a>
                </h1>
                <hr>

                {% if tasks|length == 0 %}
                    <p class="subtitle is-5 has-text-centered">No tasks found.</p>
                {% else %}
                    <table class="table is-striped  is-hoverable is-fullwidth">
                        <thead>
                        <tr>
                            <th>Sr. No</th>
                            <th>Task</th>
                            <th>Status</th>
                            <th>Team</th>
                            <th>Assignee</th>
                            <th>Created by</th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        {% include "todo\tbody2.html" %}
                    </table>
                {% endif %}

            </div>
            <div class="column"></div>
            <div class="column is-4">
                <h1 class="title is-4">Your Teams <a href="{% url 'access:create_team' %}" style="margin-left:5px;"><i
                        class="far fa-plus-square fa-sm"></i></a></h1>
                <hr>

                {% if teams|length == 0 %}
                    <p class="subtitle is-5 has-text-centered">No teams found.</p>
                {% else %}
                    <table class="table is-striped  is-hoverable is-fullwidth">
                        <thead>
                        <tr>
                            <th>Team</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for team in teams %}
                            <tr>
                                <td>
                                    {{ team.team_name }}
                                </td>
                                <td>
                                    <a
                                            href="{% url 'access:team_detail' team.id %}"
                                            class="button is-small is-outlined is-info">
                                        View
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

access/templates/access/create_team.html
{% extends 'access\base_layout.html' %}

{% block content %}

    {% include "todo\navbar.html" %}

    <div class="container">

        <div class="columns" style="margin-top:10px;padding : 15px;">
            <div class="column"></div>
            <div class="column">
                <h1 class="title is-3 has-text-centered">Create Team</h1>
                <hr>

                <form action="{% url 'access:create_team' %}" method="POST">
                    {% csrf_token %}

                    <!-- TEAM NAME-->
                    <div class="field">
                        <label class="label">Team name</label>
                        <div class="control">
                            <input class="input" type="text" placeholder="Team name" name="team_name" required>
                        </div>
                    </div>

                    <!-- Members -->
                    <div class="field">
                        <label class="label">Members</label>
                        <div class="select is-multiple is-fullwidth">
                            <select name="members" multiple>
                                {% for user in users %}
                                    <option value="{{ user }}">{{ user | title }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <!-- Buttons -->

                    <div class="columns">

                        <div class="column">
                            <div style="text-align:center;margin-top:120px;">
                                <input class="button is-info is-outlined" type="button" value=" Back " onclick="history.back()">
                            </div>
                        </div>
    
                        <div class="column">
                            <div style="text-align:center;margin-top:120px;">
                                <input class="button is-primary is-outlined" type="submit" value="CREATE">
                            </div>
                        </div>
                        
                        <div class="column">
                            <div style="text-align:center;margin-top:120px;">
                                <input class="button is-info is-outlined" type="button" value=" Back " onclick="history.back()">
                            </div>
                        </div>
    
                    </div> <!-- End Buttons -->

                </form>

            </div>
            <div class="column"></div>
        </div>


    </div>

{% endblock %}

access/templates/access/home.html
{% extends 'access\base_layout.html' %}

{% block content %}

    {% include "todo\navbar.html" %}

    <div class="container" style="margin-top:20px;">

        {% if messages %}
            <div class="columns" style="margin-top: 20px;">
                <div class="column"></div>
                <div class="column is-8">
                    <article class="message is-danger">
                        <div class="message-body">
                            <ul class="messages">
                                {% for message in messages %}
                                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </article>
                </div>
                <div class="column"></div>
            </div>
        {% endif %}


        <div class="columns">
            <div class="column is-7">
                <h1 class="title is-4">Tasks
                    <a href="{% url 'tasks:create' %}" style="margin-left:5px;">
                        <i class="far fa-plus-square fa-sm"></i>
                    </a>
                </h1>
                <hr>

                {% if tasks|length == 0 %}
                    <p class="subtitle is-5 has-text-centered">No tasks found.</p>
                {% else %}
                    <table class="table is-striped  is-hoverable is-fullwidth">
                        <thead>
                        <tr>
                            <th>Sr. No</th>
                            <th>Task</th>
                            <th>Status</th>
                            <th>Team</th>
                            <th>Assignee</th>
                            <th>Created by</th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        {% include "todo\tbody1.html" %}
                    </table>
                {% endif %}

            </div>
            <div class="column"></div>
            <div class="column is-4">
                <h1 class="title is-4">Your Teams <a href="{% url 'access:create_team' %}" style="margin-left:5px;"><i
                        class="far fa-plus-square fa-sm"></i></a></h1>
                <hr>

                {% if teams|length == 0 %}
                    <p class="subtitle is-5 has-text-centered">No teams found.</p>
                {% else %}
                    <table class="table is-striped  is-hoverable is-fullwidth">
                        <thead>
                        <tr>
                            <th>Team</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for team in teams %}
                            <tr>
                                <td>
                                    {{ team.team_name }}
                                </td>
                                <td>
                                    <a
                                            href="{% url 'access:team_detail' team.id %}"
                                            class="button is-small is-outlined is-info">
                                        View
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

access/templates/access/team_detail.html
{% extends 'access\base_layout.html' %}
{% load static %}

{% block extrahead %}
    <script src="{% static 'main.js' %}"></script>
{% endblock %}

{% block content %}

    {% include "todo\navbar.html" %}

    <div class="container">

        {% if messages %}
            <div class="columns" style="margin-top: 20px;">
                <div class="column"></div>
                <div class="column is-8">
                    <article class="message is-danger">
                        <div class="message-body">
                            <ul class="messages">
                                {% for message in messages %}
                                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </article>
                </div>
                <div class="column"></div>
            </div>
        {% endif %}


        <h1 class="title has-text-centered" style="margin-top:15px;">{{ team.team_name }}</h1>
        <hr>

        <div class="columns">
            <!-- Tasks section -->
            <div class="column is-6">
                <h1 class="title is-4">
                    Tasks
                    <a style="margin-left:5px;" onclick="toggleForm()">
                        <i class="far fa-plus-square fa-sm"></i>
                    </a>
                </h1>
                <hr>

                <!-- TASK FORM -->
                <form method="POST" action="{% url 'tasks:create' %}" id="task_form" style="display: none;">
                    {% csrf_token %}

                    <input type="hidden" name="team_id" value="{{ team.id }}">

                    <!-- TASK TITLE-->
                    <div class="field">
                        <label class="label">Title</label>
                        <div class="control">
                            <input class="input" type="text" placeholder="Task title" name="title" required>
                        </div>
                    </div>

                    <!-- DESCRIPTION -->
                    <div class="field">
                        <label class="label">Description</label>
                        <div class="control">
                            <textarea class="textarea" placeholder="Task Description" name="description"></textarea>
                        </div>
                    </div>

                    <!-- STATUS -->
                    <div class="field">
                        <label for="" class="label">Status</label>
                        <div class="control">
                            <div class="select is-fullwidth">
                                <select name="status" required>
                                    <option value="Planned">Planned</option>
                                    <option value="Ongoing">Ongoing</option>
                                    <option value="Done">Done</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <!-- ASSIGNEE -->
                    <div class="field">
                        <label for="" class="label">Assigned To</label>
                        <div class="select is-multiple is-fullwidth">
                            <select name="assignee" id="assignee" multiple>
                                {% for member in team.members.all %}
                                    <option value="{{ member }}"
                                    {% if request.user == member %}selected{% endif %}
                                    >{{ member | title }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div style="text-align:center;margin-top:120px;">
                        <input class="button is-primary is-outlined" type="submit" value="CREATE">
                    </div>
                </form>

                <!-- TASK TABLE -->
                {% if tasks|length == 0 %}
                    <p class="subtitle is-5 has-text-centered" id="task_table">No tasks found.</p>
                {% else %}
                    <table class="table is-striped  is-hoverable is-fullwidth" id="task_table">
                        <thead>
                        <tr>
                            <th>Sr. No</th>
                            <th>Task</th>
                            <th>Status</th>
                            <th>Assignee</th>
                            <th>Created by</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for task in tasks %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>
                                    <a href="{% url 'tasks:detail' task.id %}"
                                       style="color:#363636;">{{ task.title | truncatechars:15 }}</a>
                                </td>
                                <td>{{ task.status }}</td>
                                <td>
                                    {% for assignee in task.assigned_to.all %}
                                        {% if not forloop.first %}, {% endif %}
                                        {{ assignee | title }}
                                    {% endfor %}
                                </td>
                                <td>{{ task.created_by }}</td>
                                <td><a href="{% url 'tasks:detail' task.id %}"
                                       class="button is-small is-outlined is-info">View</a></td>
                                <td>
                                    {% if task.created_by == request.user %}
                                        <a href="{% url 'tasks:delete' task.id %}"
                                           class="button is-small is-outlined is-danger">
                                            Delete
                                        </a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}


            </div>
            <div class="column"></div>
            <!-- Members section-->
            <div class="column is-3">
                <h1 class="title is-4">Members</h1>
                <hr>
                <ul>
                    {% for member in team.members.all %}
                        <li class="subtitle is-6" style="margin-bottom:10px;">
                            <b>{{ forloop.counter }}. {{ member | title }}
                                {% if team.created_by == member %}
                                    <span class="tag is-info">Admin</span>
                                {% endif %}
                            </b>
                        </li>
                    {% endfor %}
                </ul>

                <form action="{% url 'access:add_team_member' %}" method="POST" style="margin-top: 20px;">
                    {% csrf_token %}
                    <input type="hidden" name="team_id" value="{{ team.id }}">
                    <div class="field">
                        <label class="label" for="members">Add Members</label>
                        <div class="select is-multiple is-fullwidth">
                            <select name="members" id="members" multiple>
                                {% for user in users %}
                                    {% if user not in team.members.all %}
                                        <option value="{{ user }}">{{ user|title }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div style="text-align:center;margin-top:120px;">
                        <input class="button is-small is-primary is-outlined" type="submit" value="Add">
                    </div>
                </form>

            </div>
        </div>
    </div>

{% endblock %}