access/urls.py
from django.contrib import admin
from django.urls import path
from access import views
from access.views import *

app_name = "access"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('home/', views.home_view, name="home"),
    path('complete_archive_all/', views.complete_archive_all, name="complete_archive_all"),
    path('logout/', views.logout_view, name="logout"),
    path('create_team/', views.create_team, name="create_team"),
    path('team/<int:team_id>/', views.team_detail, name="team_detail"),
    path('team/add_member/', views.add_team_member, name="add_team_member"),
    path('friends/<int:friends_id>/', views.friends_detail, name="friends_detail"),
    path('friends/add_member/', views.add_friends_member, name="add_friends_member"),
]

base/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('depiction/',include('depiction.urls')),
    path('', include('navigation.urls')),
    path('access/', include('access.urls')),
    path('tasks/', include('todo.urls')),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='password-reset/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

navigation/urls.py
from django.contrib import admin
from django.urls import path
from navigation import views
from navigation.views import *

app_name = "navigation"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/',views.about,name='about'),
    path('home/',views.home,name='home'),
]

navigation/models.py
from django.db import models

# Create your models here.

navigation/views.py
from django.shortcuts import render, redirect 

# Create your views here.

def index(request):
    return redirect('navigation:home')

def about(request):
    return render(request,'about/about.html', {})

def home(request):
    return render(request,'home/home.html', {})

navigation/templates/home/home.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'logo/logo.png' %}">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'navigation\home.css' %}">
</head>
<body>
<section>

    <header>
        <h2><a href="{% url 'access:home' %}" class="logo">TODO</a></h2>
        <div class="navigation">
            {% if user.is_authenticated %}
                <a href="{% url 'navigation:home' %}">Home</a>
                <a href="{% url 'navigation:about' %}">About Us</a>
                <a href="{% url 'access:login' %}">To-Do</a>
            {% else %}
                <a href="{% url 'navigation:home' %}">Home</a>
                <a href="{% url 'navigation:about' %}">About US</a>
                <a href="{% url 'access:register' %}">Sign Up</a>
                <a href="{% url 'access:login' %}">Login</a>
            {% endif %}
        </div>
    </header>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <div class="content">
        <div class="info">
            <h2>Have A Nice Journey<br><span>With US!</span></h2>
            <p>{% lorem 1 b random %}</p>
            <a href="{% url 'navigation:about' %}" class="info-btn">More Info</a>
        </div>
    </div>
    <br>
    <br>
    <div class="media-icons">
        <a href="https://www.facebook.com/aliahasan.dhaka/"><i class="fab fa-facebook-f"></i></a>
        <a href="https://twitter.com/AliAhasanRaiyan"><i class="fab fa-twitter"></i></a>
        <a href="https://www.instagram.com/aliahasanraiyan/"><i class="fab fa-instagram"></i></a>
    </div>
</section>
<footer>
    <div class="footer-text">
        &copy; 2023 - Todo App. All rights reserved.
    </div>
    <div class="theme-colors">
        <div class="theme-color blue" onclick="changeThemeColor('#1565c0')"></div>
        <div class="theme-color turquoise" onclick="changeThemeColor('#00bcd4')"></div>
        <div class="theme-color gold" onclick="changeThemeColor('#ffc107')"></div>
    </div>
</footer>

<script>
    function changeThemeColor(color) {
        document.documentElement.style.setProperty('--primary-color', color);
    }
</script>
</body>
</html>