access/urls.py
from django.contrib import admin
from django.urls import path
from access import views
from access.views import *

app_name = "access"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('home/', views.home_view, name="home"),
    path('complete_archive_all/', views.complete_archive_all, name="complete_archive_all"),
    path('logout/', views.logout_view, name="logout"),
    path('create_team/', views.create_team, name="create_team"),
    path('team/<int:team_id>/', views.team_detail, name="team_detail"),
    path('team/add_member/', views.add_team_member, name="add_team_member"),
    path('friends/<int:friends_id>/', views.friends_detail, name="friends_detail"),
    path('friends/add_member/', views.add_friends_member, name="add_friends_member"),
]

base/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('depiction/',include('depiction.urls')),
    path('', include('navigation.urls')),
    path('access/', include('access.urls')),
    path('tasks/', include('todo.urls')),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='password-reset/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

depiction/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "depiction"

urlpatterns = [
    path('<int:pk>/edit_profile_page/',EditProfilePageView.as_view(),name='edit_profile_page'),
    path('<int:pk>/profile/',ShowProfilePageView.as_view(),name='show_profile_page'),
    path('password/',PasswordsChangeView.as_view(template_name='depiction/change-password.html'), name='password'),
    path('password_success/', views.password_success, name="password_success"),
]

navigation/urls.py
from django.contrib import admin
from django.urls import path
from navigation import views
from navigation.views import *

app_name = "navigation"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/',views.about,name='about'),
    path('home/',views.home,name='home'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path
from todo import views


from todo.views import *

app_name = "tasks"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('create/', views.create_task, name='create'),
    path('<int:task_id>/', views.detail, name='detail'),
    path('edit/', views.edit, name='edit'),
    path('delete/<int:task_id>/', views.delete, name='delete'),
    path('complete_archive/<int:task_id>/', views.complete_archive, name='complete_archive'),
    path('not_complete_archive/<int:task_id>/', views.not_complete_archive, name='not_complete_archive'),
    path('comment/<int:task_id>', views.post_comment, name='comment'),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from access.models import Team

# Create your models here.

class Task(models.Model):
    STATUS_CHOICES = (
        ('Planned', 'Planned'),
        ('Ongoing', 'Ongoing'),
        ('Done', 'Done')
    )

    BOOLEAN_ASSIST = (
        ('False', 'False'),
        ('True', 'True')
    )

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    created_date = models.DateField(
        default=timezone.now, blank=True, null=True)
    created_by = models.ForeignKey(
        User, null=True, related_name='task_created_by', on_delete=models.CASCADE)
    # assigned_to = models.ForeignKey(
    #     User, blank=True, null=True, related_name='task_assigned_to', on_delete=models.CASCADE)
    assigned_to = models.ManyToManyField(User, related_name='task_assigned_to')
    team = models.ForeignKey(Team, null=True, on_delete=models.CASCADE)
    complete_archive = models.CharField(max_length=8, choices=BOOLEAN_ASSIST, default='False')

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body

todo/views.py
# from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.contrib import messages

from .models import Task, Comment, Team
from access.models import Friends


@login_required(login_url='access:login')
def create_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        status = request.POST.get('status')
        assignees = request.POST.getlist('assignee')

        task = Task(title=title, description=description,
                    status=status, created_by=request.user)

        team_id = request.POST.get('team_id', None)

        if team_id is not None:
            try:
                team = Team.objects.get(pk=team_id)
                task.team = team
            except Team.DoesNotExist:
                return redirect('access:home')

        task.save()

        if len(assignees) == 0:
            task.assigned_to.add(request.user)

        for assignee in assignees:
            task.assigned_to.add(User.objects.get(username=assignee))

        task.save()

        '''
        If request from team page, then redirect back to team
        '''
        if team_id is not None:
            return redirect('access:team_detail', team_id=team_id)

        return redirect('access:home')

    users = User.objects.all()
    friends = Friends.objects.get(pk=request.user.id) # added after 2nd update
    # members = friends.members.all() #testings # added after 2nd update
    # print(members) #testings # added after 2nd update

    return render(request, 'todo/create.html', {'users': users, "friends": friends,})


@login_required(login_url='access:login')
def detail(request, task_id):
    try:
        task = Task.objects.get(pk=task_id)
    except Task.DoesNotExist:
        return redirect('access:home')

    team = task.team

    if team is None:
        ''' Check whether user can view details of another task '''
        if request.user != task.created_by and request.user not in task.assigned_to.all():
            messages.error(request, "You can't view this task")
            return redirect('access:home')
    else:
        if request.user not in team.members.all():
            messages.error(request, "You can't view this task")
            return redirect('access:home')

    users = User.objects.all()

    comments = Comment.objects.filter(task=task)

    friends = Friends.objects.get(pk=request.user.id) # added after 2nd update

    statuses = ['Planned', 'Ongoing', 'Done']

    return render(request, "todo/detail.html", {
        "id": task_id, "task": task,
        "users": users, "statuses": statuses,
        "comments": comments, "friends": friends,
    })


@login_required(login_url='access:login')
def edit(request):
    if request.method == 'POST':
        try:
            task = Task.objects.get(pk=request.POST.get("task_id"))
        except Task.DoesNotExist:
            messages.error(request, "Task not found")
            return redirect('access:home')

        title = request.POST.get('title')
        description = request.POST.get('description')
        status = request.POST.get('status')
        assignees = request.POST.getlist('assignee')

        task.title = title
        task.description = description
        task.status = status

        for assignee in assignees:
            task.assigned_to.add(User.objects.get(username=assignee))

        task.save()

        return redirect('access:home')

    return redirect('access:home')


@login_required(login_url='access:login')
def delete(request, task_id):
    try:
        task = Task.objects.get(pk=task_id)
    except Task.DoesNotExist:
        messages.error(request, "Task doesn't exist")
        return redirect('access:home')

    if task:
        if request.user == task.created_by:
            task.delete()
        else:
            messages.error(request, "Only task creator can delete task.")
    else:
        messages.error(request, "Task doesn't exist")

    return redirect('access:home')


@login_required()
def post_comment(request, task_id):
    try:
        task = Task.objects.get(pk=task_id)
    except Task.DoesNotExist:
        messages.error(request, "Task doesn't exist")
        return redirect('access:home')

    if request.method == 'POST':
        body = request.POST.get("comment")
        team_id = request.POST.get("team_id", None)

        flag = False

        # If team is none, check if user created/assigned task
        if team_id is None:
            if request.user == task.created_by or request.user in task.assigned_to.all():
                flag = True
            else:
                messages.error(request, "You can't comment on this task")
        else:
            team = Team.objects.get(pk=team_id)
            # Check if user is present in team
            if request.user in team.members.all():
                flag = True
            else:
                messages.error(
                    request, "Only team members can comment on this task")

        if flag:
            comment = Comment(body=body, author=request.user, task=task)
            comment.save()

        # print(body)

    return redirect('tasks:detail', task_id=task_id)


# ----------------------------------------- After 2nd Update -------------------------------------------------------

@login_required(login_url='access:login')
def complete_archive(request, task_id):
    try:
        task = Task.objects.get(pk=task_id)
    except Task.DoesNotExist:
        messages.error(request, "Task doesn't exist")
        return redirect('access:home')

    if task:
        # if request.user == task.created_by or request.user in task.assigned_to.all():
        if request.user == task.created_by:
            task.complete_archive = 'True'
            task.save()
        else:
            messages.error(request, "Only task creator can archive task.")
    else:
        messages.error(request, "Task doesn't exist")

    return redirect('access:home')


@login_required(login_url='access:login')
def not_complete_archive(request, task_id):
    try:
        task = Task.objects.get(pk=task_id)
    except Task.DoesNotExist:
        messages.error(request, "Task doesn't exist")
        return redirect('access:home')

    if task:
        # if request.user == task.created_by or request.user in task.assigned_to.all():
        if request.user == task.created_by:
            task.complete_archive = 'False'
            task.save()
        else:
            messages.error(request, "Only task creator can restore task.")
    else:
        messages.error(request, "Task doesn't exist")

    return redirect('access:complete_archive_all')

todo/templates/todo/detail.html
{% extends 'access\base_layout.html' %}

{% block content %}

    {% include "todo\navbar.html" %}

    {% if messages %}
        <div class="columns" style="margin-top: 20px;">
            <div class="column"></div>
            <div class="column is-8">
                <article class="message is-danger">
                    <div class="message-body">
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </article>
            </div>
            <div class="column"></div>
        </div>
    {% endif %}

    <div class="columns" style="margin-top:10px;padding : 15px;">
        <div class="column"></div>
        <div class="column">
            <h1 class="title is-3 has-text-centered">{{ task.title }}</h1>
            <hr>
            <!-- TASK DETAIL -->
            <form method="POST" action="{% url 'tasks:edit' %}">
                {% csrf_token %}

                <input type="hidden" value="{{ task.id }}" name="task_id">

                <!-- TASK TITLE-->
                <div class="field">
                    <label class="label">Title</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="Task title" name="title" value="{{ task.title }}"
                               required {% if task.created_by != request.user %}disabled="disabled"{% endif %}>
                    </div>
                </div>

                <!-- DESCRIPTION -->
                <div class="field">
                    <label class="label">Description</label>
                    <div class="control">
                        <textarea class="textarea" placeholder="Task description" name="description"
                                  {% if task.created_by != request.user %}disabled="disabled"{% endif %}>{{ task.description }}</textarea>
                    </div>
                </div>

                <!-- STATUS -->
                <div class="field">
                    <label for="" class="label">Status</label>
                    <div class="control">
                        <div class="select is-fullwidth">
                            <select name="status" required
                                    {% if task.created_by != request.user %}disabled="disabled"{% endif %}>
                                {% for status in statuses %}
                                    <option
                                            {% if  status == task.status %}selected="selected"{% endif %}
                                            value="{{ status }}">{{ status }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>

                {% if task.team %}
                    <!-- TASK TITLE-->
                    <div class="field">
                        <label class="label">Team</label>
                        <div class="control">
                            <input class="input" type="text" placeholder="Team" name="team_id"
                                   value="{{ task.team }}" required disabled>
                        </div>
                    </div>
                {% endif %}

                <!-- ASSIGNEE -->
                <div class="field">
                    <label for="" class="label">Assigned To</label>
                    <div class="control">
                        <div class="select is-fullwidth">
                            <select name="assignee" id="assignee"
                                    multiple required
                                    {% if task.created_by != request.user %}disabled="disabled"{% endif %}
                            >
                                {% if task.team %}
                                    {% for member in task.team.members.all %}
                                        <option value="{{ member }}"
                                                {% if member in task.assigned_to.all %}selected{% endif %}>
                                            {{ member | title }}
                                        </option>
                                    {% endfor %}
                                {% else %}
                                    {% for friend in friends.members.all %}
                                        <option value="{{ friend }}"
                                                {% if friend in task.assigned_to.all %}selected{% endif %}>
                                            {{ friend | title }}
                                        </option>
                                    {% endfor %}
                                {% endif %}
                            </select>
                        </div>
                    </div>
                </div>

                <!-- Buttons -->

                <div class="columns">

                    <div class="column">
                        <div style="text-align:center;margin-top:120px;">
                            <input class="button is-info is-outlined" type="button" value=" Back " onclick="history.back()">
                        </div>
                    </div>

                    <div class="column">
                        {% if task.created_by == request.user %}
                        <div style="text-align:center;margin-top:120px;">
                            <input class="button is-info is-outlined" type="submit" value="DONE">
                        </div>
                        {% endif %}
                    </div>
                    
                    <div class="column">
                        <div style="text-align:center;margin-top:120px;">
                            <input class="button is-info is-outlined" type="button" value=" Back " onclick="history.back()">
                        </div>
                    </div>

                </div> <!-- End Buttons -->

                
            </form>


        </div>
        <div class="column"></div>

    </div>

    <div class="columns" style="margin-top: 30px;padding: 20px;">
        <div class="column"></div>
        <div class="column is-8">
            <h1 class="title is-5">Comments</h1>
            <hr>

            {% for comment in comments %}
                <article class="media">
                    <figure class="media-left">
                        <p class="image is-32x32">
                            <img src="https://ui-avatars.com/api/?background=0D8ABC&color=fff&size=196&name={{ comment.author }}" alt="{{ comment.author }}">
                        </p>
                    </figure>
                    <div class="media-content">
                        <div class="content">
                            <p>
                                <strong>{{ comment.author | title }}</strong>
                                <br>
                                {{ comment.body }}
                                <br>
                                <small>{{ comment.created_at }}</small>
                            </p>
                        </div>
                    </div>
                </article>
            {% endfor %}


            <article class="media">
                <figure class="media-left">
                    <p class="image is-32x32">
                        <img src="https://ui-avatars.com/api/?background=0D8ABC&color=fff&size=196&name={{ request.user }}" alt="{{ request.user }}">
                    </p>
                </figure>
                <div class="media-content">
                    <form action="{% url 'tasks:comment' task.id %}" method="POST">
                        {% csrf_token %}

                        {% if task.team %}
                            <input type="hidden" name="team_id" value="{{ task.team.id }}">
                        {% endif %}

                        <div class="field">
                            <p class="control">
                                <textarea class="textarea" placeholder="Add a comment..." name="comment"></textarea>
                            </p>
                        </div>
                        <div class="field">
                            <input class="button is-primary is-outlined" type="submit" value="Post Comment">
                        </div>
                    </form>
                </div>
            </article>
        </div>
        <div class="column"></div>
    </div>

{% endblock %}

todo/templates/todo/navbar.html
{% load  static %}
<nav id="navbar" class="navbar is-dark">

    <div class="navbar-brand">
        <a href="{% url 'access:home' %}" class="navbar-item"><img src="{% static 'logo/logo.png' %}"></a>
        <div
                id="navbarBurger"
                class="navbar-burger burger"
                data-target="burgerMenu"
        >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </div>
    </div>

    <div class="navbar-brand">
        <a href="{% url 'access:home' %}" class="navbar-item">{{ request.user }}</a>
        <div
                id="navbarBurger"
                class="navbar-burger burger"
                data-target="burgerMenu"
        >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </div>
    </div>

    <div class="navbar-item">
        <a href="{% url 'access:complete_archive_all' %}" class="navbar-item">Archive</a>
        <div
                id="navbarBurger"
                class="navbar-burger burger"
                data-target="burgerMenu"
        >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </div>
    </div>

    <div class="navbar-item">
        {% comment %} {% if friends_name.friends.id != 1 %}
        <a href="{% url 'access:create_friends' %}" class="navbar-item">Friends</a>
        {% elif friends_name.friends.id == 1 %} {% endcomment %}
        <a href="{% url 'access:friends_detail' request.user.id %}" class="navbar-item">Friends</a>
        {% comment %} {% endif %} {% endcomment %}
        <div
                id="navbarBurger"
                class="navbar-burger burger"
                data-target="burgerMenu"
        >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </div>       
   </div>

   <div class="navbar-item">
        {% comment %} <a href="{% url 'edit_profile_page' user.profile.id %}" class="navbar-item">Profile</a> {% endcomment %}
        <a href="{% url 'depiction:show_profile_page' user.profile.id %}" class="navbar-item">Profile</a>
        <div
                id="navbarBurger"
                class="navbar-burger burger"
                data-target="burgerMenu"
        >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </div>       
    </div>

    <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a href="{% url 'navigation:home' %}" class="navbar-item">
            Home
          </a>
          <hr class="navbar-divider">
          <a href="{% url 'navigation:about' %}" class="navbar-item">
            About
          {% comment %} </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a> {% endcomment %}
        </div>

        <div
                id="navbarBurger"
                class="navbar-burger burger"
                data-target="burgerMenu"
        >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </div> 

    </div>

    <div class="navbar-menu" id="burgerMenu">
        <div class="navbar-end">
            <a href="{% url 'access:logout' %}" class="navbar-item">
                <strong>Logout</strong>
            </a>
        </div>
    </div>
    
</nav>

{% include "nav_music_player\nav_music_player.html" %}

<script>
    document.addEventListener('DOMContentLoaded', () => {

        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

        // Check if there are any navbar burgers
        if ($navbarBurgers.length > 0) {

            // Add a click event on each of them
            $navbarBurgers.forEach(el => {
                el.addEventListener('click', () => {

                    // Get the target from the "data-target" attribute
                    const target = el.dataset.target;
                    const $target = document.getElementById(target);

                    // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                    el.classList.toggle('is-active');
                    $target.classList.toggle('is-active');

                });
            });
        }

    });
</script>

todo/templates/todo/tbody1.html
<tbody>
    {% for task in tasks %}
        {% if task.complete_archive != 'True' %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'tasks:detail' task.id %}"
                   style="color:#363636;">{{ task.title | truncatechars:15 }}</a>
            </td>
            <td>{{ task.status }}</td>
            <td>{{ task.team }}</td>
            <td>
                {% for assignee in task.assigned_to.all %}
                    {% if not forloop.first %}, {% endif %}
                    {{ assignee | title }}
                {% endfor %}
            </td>
            <td>{{ task.created_by }}</td>
            <td><a href="{% url 'tasks:detail' task.id %}"
                   class="button is-small is-outlined is-info">View</a></td>
            <td>
                {% if task.created_by == request.user %}
                    <a href="{% url 'tasks:delete' task.id %}"
                       class="button is-small is-outlined is-danger">
                        Delete
                    </a>
                {% endif %}
            </td>
            <td>
                {% if task.created_by == request.user and task.team == null %}
                    <a href="{% url 'tasks:complete_archive' task.id %}"
                       class="button is-small is-outlined is-success">
                        Archive
                    </a>
                {% endif %}
            </td>
        </tr>
        {% endif %}
    {% endfor %}
</tbody>

todo/templates/todo/tbody2.html
<tbody>
    {% for task in tasks %}
        {% if task.complete_archive == 'True' %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'tasks:detail' task.id %}"
                   style="color:#363636;">{{ task.title | truncatechars:15 }}</a>
            </td>
            <td>{{ task.status }}</td>
            <td>{{ task.team }}</td>
            <td>
                {% for assignee in task.assigned_to.all %}
                    {% if not forloop.first %}, {% endif %}
                    {{ assignee | title }}
                {% endfor %}
            </td>
            <td>{{ task.created_by }}</td>
            <td><a href="{% url 'tasks:detail' task.id %}"
                   class="button is-small is-outlined is-info">View</a></td>
            <td>
                {% if task.created_by == request.user %}
                    <a href="{% url 'tasks:delete' task.id %}"
                       class="button is-small is-outlined is-danger">
                        Delete
                    </a>
                {% endif %}
            </td>
            <td>
                {% if task.created_by == request.user and task.team == null %}
                    <a href="{% url 'tasks:not_complete_archive' task.id %}"
                       class="button is-small is-outlined is-warning">
                        Restore
                    </a>
                {% endif %}
            </td>
        </tr>
        {% endif %}
    {% endfor %}
</tbody>